# Generated by Django 5.2.1 on 2025-05-31 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_preference', models.CharField(choices=[('ar', 'Arabic'), ('he', 'Hebrew'), ('en', 'English')], default='he', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('hint', models.TextField(blank=True)),
                ('arabic_text', models.CharField(max_length=255)),
                ('hebrew_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vocabulary Entries',
                'ordering': ['concept'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(db_index=True, max_length=100)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('he', 'Hebrew'), ('en', 'English')], max_length=2)),
                ('text', models.CharField(max_length=255)),
                ('hint', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Vocabulary',
                'unique_together': {('concept', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GameResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100)),
                ('selected_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.gamesession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'submitted_at'], name='core_gamere_session_2c7989_idx'), models.Index(fields=['is_correct'], name='core_gamere_is_corr_c25043_idx')],
            },
        ),
    ]
